import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { ApiService } from '../../core/services/api.service';

type Stage='SAVED'|'APPLIED'|'SCREENING'|'INTERVIEW'|'TECHNICAL'|'OFFER'|'REJECTED'|'WITHDRAWN';
type App={id:string;title:string;company:string;stage:Stage;source?:string;applicationUrl?:string;jobAnalysisId?:string|null;appliedAt?:string;nextFollowUpAt?:string;recruiterName?:string;recruiterEmail?:string;notes:Array<{body:string;createdAt:string}>};
type Pipeline={counts:Record<string,number>;applications:App[]};
type Job={id:string;title:string;company?:string};
type Prep={application:{id:string;title:string;company:string;stage:Stage;recruiterName?:string;nextFollowUpAt?:string};talkingPoints:string[];interviewQuestions:string[];preparationChecklist:string[];hasJobAnalysis:boolean};

@Component({standalone:true,imports:[FormsModule,RouterLink,MatButtonModule],template:`
<section class="apps page-enter">
  <div class="page-head"><div><span class="eyebrow">Career workspace</span><h1>Applications & interviews</h1><p class="muted">Track each opportunity from saved role to offer, keep recruiter notes, schedule follow-ups and prepare interviews from evidence already stored in LearnFlow.</p></div><a mat-stroked-button routerLink="/career/jobs">Job matching</a></div>
  @if(error()){<div class="error">{{error()}}</div>}
  <div class="top-grid"><article class="card"><span class="mini-label">Add opportunity</span><h2>New application</h2><div class="form"><input [(ngModel)]="draft.title" placeholder="Role title"><input [(ngModel)]="draft.company" placeholder="Company"><select [(ngModel)]="draft.jobAnalysisId"><option value="">No linked job analysis</option>@for(job of jobs();track job.id){<option [value]="job.id">{{job.title}} · {{job.company||'Unknown company'}}</option>}</select><div class="pair"><input [(ngModel)]="draft.source" placeholder="Source (LinkedIn, OfferZen...)"/><input [(ngModel)]="draft.applicationUrl" placeholder="Application URL"/></div><div class="pair"><input [(ngModel)]="draft.recruiterName" placeholder="Recruiter name"/><input [(ngModel)]="draft.recruiterEmail" placeholder="Recruiter email"/></div><button mat-flat-button class="primary-cta" (click)="create()" [disabled]="busy()||draft.title.trim().length<2||draft.company.trim().length<2">{{busy()?'Saving…':'Add to pipeline'}}</button></div></article>
  <article class="card summary"><span class="mini-label">Pipeline health</span><h2>{{pipeline().applications.length}} opportunities</h2><div class="summary-grid">@for(stage of activeStages;track stage){<div><span>{{label(stage)}}</span><strong>{{pipeline().counts[stage]||0}}</strong></div>}</div><p class="muted">Follow-ups due: <strong>{{followUpsDue()}}</strong></p></article></div>

  <section class="board">@for(stage of stages;track stage){<div class="column"><header><strong>{{label(stage)}}</strong><span>{{pipeline().counts[stage]||0}}</span></header><div class="cards">@for(item of byStage(stage);track item.id){<article class="app-card" (click)="select(item)"><div class="card-title"><strong>{{item.title}}</strong><small>{{item.company}}</small></div><select [ngModel]="item.stage" (ngModelChange)="move(item,$event)" (click)="$event.stopPropagation()">@for(option of stages;track option){<option [value]="option">{{label(option)}}</option>}</select>@if(item.recruiterName){<small>Recruiter · {{item.recruiterName}}</small>}@if(item.nextFollowUpAt){<small [class.due]="isDue(item.nextFollowUpAt)">Follow up · {{date(item.nextFollowUpAt)}}</small>}@if(item.jobAnalysisId){<span class="analysis-chip">Job analysis linked</span>}</article>}@empty{<div class="empty">No applications</div>}</div></div>}</section>

  @if(selected();as item){<section class="drawer card"><div class="drawer-head"><div><span class="mini-label">Application detail</span><h2>{{item.title}} · {{item.company}}</h2></div><button type="button" class="close" (click)="selected.set(null)">×</button></div><div class="detail-grid"><div><label>Follow-up date</label><input type="date" [ngModel]="dateInput(item.nextFollowUpAt)" (ngModelChange)="setFollowUp(item,$event)"></div><div><label>Application link</label>@if(item.applicationUrl){<a [href]="item.applicationUrl" target="_blank" rel="noopener">Open application ↗</a>}@else{<span class="muted">Not recorded</span>}</div></div><div class="drawer-columns"><article><h3>Notes</h3><div class="note-form"><textarea [(ngModel)]="note" rows="3" placeholder="Recruiter call, salary, interview feedback, next action..."></textarea><button mat-stroked-button (click)="addNote(item)" [disabled]="!note.trim()">Add note</button></div>@for(entry of item.notes;track entry.createdAt){<div class="note"><p>{{entry.body}}</p><small>{{dateTime(entry.createdAt)}}</small></div>}@empty{<p class="muted">No notes yet.</p>}</article><article><div class="prep-head"><h3>Interview prep</h3><button mat-flat-button class="primary-cta" (click)="prepare(item)">Load prep</button></div>@if(prep();as p){@if(!p.hasJobAnalysis){<div class="warning">Link a Job Matching analysis to unlock role-specific evidence and interview questions.</div>}<h4>Checklist</h4>@for(check of p.preparationChecklist;track check){<div class="check">□ {{check}}</div>}<h4>Evidence talking points</h4>@for(point of p.talkingPoints;track point){<div class="talk">✓ {{point}}</div>}@empty{<p class="muted">No evidence-backed talking points yet.</p>}<h4>Likely questions</h4>@for(q of p.interviewQuestions;track q){<div class="question">{{q}}</div>}}@else{<p class="muted">Load prep to build an interview checklist from the linked analysis.</p>}</article></div></section>}
</section>`,styles:[`
.apps{max-width:1400px;margin:0 auto}.top-grid{display:grid;grid-template-columns:1.4fr .8fr;gap:16px}.card{background:#fff;border:1px solid #dfe5ed;border-radius:18px;padding:20px}.form{display:grid;gap:10px}.form input,.form select,.drawer input,.drawer textarea,.app-card select{border:1px solid #d7dde7;border-radius:10px;padding:10px;font:inherit;background:#fff}.pair{display:grid;grid-template-columns:1fr 1fr;gap:10px}.summary-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.summary-grid div{border:1px solid #e6ebf2;border-radius:12px;padding:12px}.summary-grid span{display:block;color:#7a869a;font-size:.75rem}.summary-grid strong{font-size:1.4rem}.board{display:grid;grid-template-columns:repeat(8,minmax(220px,1fr));gap:12px;margin-top:18px;overflow-x:auto;padding-bottom:8px}.column{background:#f6f8fb;border:1px solid #e1e6ee;border-radius:15px;padding:10px;min-height:260px}.column header{display:flex;justify-content:space-between;align-items:center;padding:5px 4px 10px}.column header span{background:#e7edf7;border-radius:999px;padding:2px 8px;font-size:.72rem}.cards{display:grid;gap:8px}.app-card{background:#fff;border:1px solid #e0e6ef;border-radius:12px;padding:12px;display:grid;gap:8px;cursor:pointer}.card-title{display:flex;flex-direction:column}.card-title small,.app-card>small{color:#7a869a}.analysis-chip{font-size:.68rem;background:#eef4ff;color:#2f6fed;border-radius:999px;padding:4px 8px;width:max-content}.due{color:#b13b47!important;font-weight:800}.empty{padding:18px 8px;color:#8a96a8;text-align:center}.drawer{margin-top:18px}.drawer-head,.prep-head{display:flex;justify-content:space-between;align-items:center}.close{border:0;background:transparent;font-size:1.7rem;cursor:pointer}.detail-grid,.drawer-columns{display:grid;grid-template-columns:1fr 1fr;gap:18px}.detail-grid{padding:12px 0 18px;border-bottom:1px solid #edf1f5}.detail-grid div{display:flex;flex-direction:column;gap:5px}.note-form{display:grid;gap:8px}.note{border-top:1px solid #edf1f5;padding:10px 0}.note p{margin:0 0 4px}.note small{color:#7a869a}.check,.talk,.question{padding:8px 0;border-top:1px solid #edf1f5}.warning,.error{padding:12px;border-radius:10px}.warning{background:#fff8e6;color:#7a5413}.error{background:#fff1f0;color:#a61b1b;margin-bottom:12px}@media(max-width:900px){.top-grid,.drawer-columns,.detail-grid{grid-template-columns:1fr}.pair{grid-template-columns:1fr}.summary-grid{grid-template-columns:repeat(2,1fr)}}
`]} )
export class ApplicationWorkspaceComponent implements OnInit{
 private readonly api=inject(ApiService);readonly pipeline=signal<Pipeline>({counts:{},applications:[]});readonly jobs=signal<Job[]>([]);readonly selected=signal<App|null>(null);readonly prep=signal<Prep|null>(null);readonly error=signal('');readonly busy=signal(false);note='';draft={title:'',company:'',jobAnalysisId:'',source:'',applicationUrl:'',recruiterName:'',recruiterEmail:''};
 readonly stages:Stage[]=['SAVED','APPLIED','SCREENING','INTERVIEW','TECHNICAL','OFFER','REJECTED','WITHDRAWN'];readonly activeStages:Stage[]=['APPLIED','SCREENING','INTERVIEW','TECHNICAL','OFFER'];
 ngOnInit(){this.refresh();this.api.get<Job[]>('/api/v1/career/jobs').subscribe({next:v=>this.jobs.set(v),error:()=>undefined});}
 refresh(){this.api.get<Pipeline>('/api/v1/career/applications').subscribe({next:v=>this.pipeline.set(v),error:e=>this.error.set(e.error?.message??'Could not load applications.')});}
 create(){this.busy.set(true);this.error.set('');const body={...this.draft,jobAnalysisId:this.draft.jobAnalysisId||undefined,source:this.draft.source||undefined,applicationUrl:this.draft.applicationUrl||undefined,recruiterName:this.draft.recruiterName||undefined,recruiterEmail:this.draft.recruiterEmail||undefined};this.api.post<typeof body,App>('/api/v1/career/applications',body).subscribe({next:()=>{this.draft={title:'',company:'',jobAnalysisId:'',source:'',applicationUrl:'',recruiterName:'',recruiterEmail:''};this.busy.set(false);this.refresh();},error:e=>{this.busy.set(false);this.error.set(e.error?.message??'Could not create application.')}});}
 byStage(stage:Stage){return this.pipeline().applications.filter(x=>x.stage===stage)}
 move(item:App,stage:Stage){this.api.patch<{stage:Stage},App>(`/api/v1/career/applications/${item.id}`,{stage}).subscribe({next:()=>this.refresh(),error:e=>this.error.set(e.error?.message??'Could not move application.')});}
 select(item:App){this.selected.set(item);this.prep.set(null);this.note='';}
 addNote(item:App){const body=this.note.trim();if(!body)return;this.api.post<{body:string},Array<{body:string;createdAt:string}>>(`/api/v1/career/applications/${item.id}/notes`,{body}).subscribe({next:notes=>{const updated={...item,notes};this.selected.set(updated);this.note='';this.refresh();},error:e=>this.error.set(e.error?.message??'Could not save note.')});}
 prepare(item:App){this.api.get<Prep>(`/api/v1/career/applications/${item.id}/interview-prep`).subscribe({next:v=>this.prep.set(v),error:e=>this.error.set(e.error?.message??'Could not load interview prep.')});}
 setFollowUp(item:App,value:string){this.api.patch<{nextFollowUpAt?:string},App>(`/api/v1/career/applications/${item.id}`,{nextFollowUpAt:value||undefined}).subscribe({next:v=>{this.selected.set(v);this.refresh();},error:e=>this.error.set(e.error?.message??'Could not update follow-up.')});}
 followUpsDue(){const now=Date.now();return this.pipeline().applications.filter(x=>x.nextFollowUpAt&&new Date(x.nextFollowUpAt).getTime()<=now&&!['REJECTED','WITHDRAWN','OFFER'].includes(x.stage)).length;}
 isDue(v:string){return new Date(v).getTime()<=Date.now()}
 label(s:Stage){return s.charAt(0)+s.slice(1).toLowerCase().replace('_',' ')}
 date(v:string){return new Intl.DateTimeFormat(undefined,{day:'numeric',month:'short',year:'numeric'}).format(new Date(v))}
 dateTime(v:string){return new Intl.DateTimeFormat(undefined,{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}
 dateInput(v?:string){return v?new Date(v).toISOString().slice(0,10):''}
}
