import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { ApiService } from '../../core/services/api.service';

type Level='FOUNDATION'|'WORKING'|'STRONG';
type EvidenceType='LESSON'|'PROJECT'|'CERTIFICATE'|'LINK';
interface LessonOption{id:string;title:string;masteryScore:number|null;confidenceScore:number|null;assessmentAttempts:number;}
interface Requirement{name:string;targetLevel:Level;currentLevel:Level|null;met:boolean;evidenceCount:number;masteryScore:number|null;}
interface Evidence{_id:string;skillName:string;evidenceType:EvidenceType;title:string;description?:string;url?:string;derivedLevel:Level;lesson?:{title:string;masteryScore:number|null}|null;}
interface Skill{key:string;name:string;level:Level;evidenceCount:number;masteryScore:number|null;evidence:Evidence[];}
interface Overview{target:{roleTitle:string;description?:string;requiredSkills:Array<{name:string;targetLevel:Level}>}|null;readiness:{score:number;metSkills:number;totalSkills:number;gaps:Requirement[];requirements:Requirement[]};portfolio:{evidenceCount:number;portfolioReadyEvidence:number;lessonEvidence:number;projectEvidence:number};skills:Skill[];}

@Component({standalone:true,imports:[FormsModule,MatButtonModule],template:`
<section class="career page-enter">
<div class="page-head"><div><span class="eyebrow">Career & skills evidence</span><h1>Turn learning into proof.</h1><p class="muted">Map a target role to evidence from mastered lessons, projects and credentials. Readiness is evidence-based, not a hiring guarantee.</p></div></div>
@if(error()){<div class="error">{{error()}}</div>}
@if(data();as d){<div class="stats"><article><span>Role readiness</span><strong>{{d.readiness.score}}%</strong><small>{{d.readiness.metSkills}} / {{d.readiness.totalSkills}} requirements evidenced</small></article><article><span>Skills evidenced</span><strong>{{d.skills.length}}</strong><small>Derived from your saved evidence</small></article><article><span>Evidence</span><strong>{{d.portfolio.evidenceCount}}</strong><small>{{d.portfolio.portfolioReadyEvidence}} portfolio-ready links</small></article><article><span>Mastery-backed</span><strong>{{d.portfolio.lessonEvidence}}</strong><small>Completed lesson evidence</small></article></div>}
<div class="grid"><article class="card"><span class="mini-label">Target role</span><h2>{{roleTitle||'Define where you are heading'}}</h2><input [(ngModel)]="roleTitle" placeholder="e.g. Senior Full-Stack Engineer"><textarea [(ngModel)]="roleDescription" rows="3" placeholder="Optional target-role context"></textarea><div class="requirements">@for(item of requirements;track $index){<div><input [(ngModel)]="item.name" placeholder="Skill"><select [(ngModel)]="item.targetLevel"><option value="FOUNDATION">Foundation</option><option value="WORKING">Working</option><option value="STRONG">Strong</option></select><button type="button" (click)="removeRequirement($index)">×</button></div>}</div><div class="actions"><button mat-stroked-button (click)="addRequirement()">Add skill</button><button mat-flat-button class="primary-cta" (click)="saveTarget()" [disabled]="!roleTitle.trim()||!validRequirements()">Save target role</button></div></article>
<article class="card"><span class="mini-label">Add evidence</span><h2>Back a skill with proof</h2><select [(ngModel)]="evidenceType"><option value="LESSON">Completed lesson</option><option value="PROJECT">Project</option><option value="CERTIFICATE">Certificate</option><option value="LINK">Reference link</option></select><input [(ngModel)]="skillName" placeholder="Skill name, e.g. Angular">@if(evidenceType==='LESSON'){<select [(ngModel)]="lessonId"><option value="">Choose completed lesson</option>@for(item of lessons();track item.id){<option [value]="item.id">{{item.title}} · mastery {{item.masteryScore??'—'}}%</option>}</select>}@else{<input [(ngModel)]="evidenceTitle" placeholder="Evidence title"><input [(ngModel)]="evidenceUrl" placeholder="https://...">}<textarea [(ngModel)]="evidenceDescription" rows="3" placeholder="What does this demonstrate?"></textarea><button mat-flat-button class="primary-cta" (click)="addEvidence()" [disabled]="!canAddEvidence()">Add evidence</button></article></div>
@if(data();as d){<article class="card"><div class="section-head"><div><span class="mini-label">Gap analysis</span><h2>{{d.target?.roleTitle || 'No target role yet'}}</h2></div></div><div class="gap-list">@for(item of d.readiness.requirements;track item.name){<div><span class="status" [class.met]="item.met">{{item.met?'✓':'!'}}</span><div><strong>{{item.name}}</strong><small>Target {{label(item.targetLevel)}} · Current {{item.currentLevel?label(item.currentLevel):'No evidence'}}</small>@if(item.masteryScore!==null){<small>Best linked mastery {{item.masteryScore}}%</small>}</div></div>}@empty{<p class="muted">Add required skills to your target role to calculate readiness.</p>}</div></article>
<article class="card"><div class="section-head"><div><span class="mini-label">Skill profile</span><h2>Evidence-backed skills</h2></div></div><div class="skill-list">@for(skill of d.skills;track skill.key){<section><div class="skill-head"><div><strong>{{skill.name}}</strong><small>{{label(skill.level)}} · {{skill.evidenceCount}} evidence item{{skill.evidenceCount===1?'':'s'}}@if(skill.masteryScore!==null){ · mastery {{skill.masteryScore}}%}</small></div><span>{{label(skill.level)}}</span></div>@for(item of skill.evidence;track item._id){<div class="evidence"><div><strong>{{item.title}}</strong><small>{{item.evidenceType}} · {{label(item.derivedLevel)}}</small>@if(item.description){<p>{{item.description}}</p>}@if(item.url){<a [href]="item.url" target="_blank" rel="noopener">Open evidence ↗</a>}</div><button type="button" (click)="removeEvidence(item._id)">Remove</button></div>}</section>}@empty{<p class="muted">Add your first evidence item to build a skill profile.</p>}</div></article>}
</section>`,styles:[`.career{max-width:1120px;margin:0 auto}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:18px}.stats article,.card{background:#fff;border:1px solid #dfe5ed;border-radius:18px;padding:20px}.stats span,.stats small{display:block;color:#7a869a}.stats span{font-size:.68rem;font-weight:850;text-transform:uppercase}.stats strong{display:block;font-size:1.7rem;color:#10233f;margin:5px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:18px}.card{margin-bottom:18px}.card h2{color:#10233f;margin:6px 0 14px}.card input,.card textarea,.card select{width:100%;box-sizing:border-box;border:1px solid #d7dde7;border-radius:10px;padding:10px;margin:5px 0;font:inherit;background:#fff}.requirements>div{display:grid;grid-template-columns:1fr 150px 36px;gap:6px}.requirements button,.evidence button{border:0;background:transparent;color:#8a4650;cursor:pointer}.actions{display:flex;gap:8px;justify-content:flex-end;margin-top:10px}.gap-list>div,.evidence{display:flex;gap:12px;padding:12px 0;border-top:1px solid #edf1f5}.status{width:28px;height:28px;border-radius:50%;display:grid;place-items:center;background:#fff1f1;color:#b13b47;font-weight:900}.status.met{background:#eaf7ef;color:#216e4e}.gap-list small,.skill-list small,.evidence small{display:block;color:#7a869a}.skill-list>section{padding:15px 0;border-top:1px solid #edf1f5}.skill-head{display:flex;justify-content:space-between;gap:10px}.skill-head>span{font-size:.65rem;font-weight:850;background:#eef4ff;color:#2f6fed;padding:6px 8px;border-radius:999px;height:max-content}.evidence{justify-content:space-between;margin-left:10px}.evidence p{margin:4px 0;color:#66758a}.evidence a{color:#2f6fed;text-decoration:none;font-weight:800;font-size:.72rem}.error{background:#fff1f0;color:#a61b1b;padding:12px;border-radius:12px;margin-bottom:14px}@media(max-width:820px){.stats{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}}@media(max-width:520px){.stats{grid-template-columns:1fr}.requirements>div{grid-template-columns:1fr}.actions{flex-direction:column}}`]})
export class CareerComponent implements OnInit{private readonly api=inject(ApiService);readonly data=signal<Overview|null>(null);readonly lessons=signal<LessonOption[]>([]);readonly error=signal('');roleTitle='';roleDescription='';requirements:Array<{name:string;targetLevel:Level}>=[{name:'',targetLevel:'WORKING'}];evidenceType:EvidenceType='LESSON';skillName='';lessonId='';evidenceTitle='';evidenceUrl='';evidenceDescription='';ngOnInit(){this.load();this.api.get<LessonOption[]>('/api/v1/career/lessons').subscribe(v=>this.lessons.set(v));}load(){this.api.get<Overview>('/api/v1/career/overview').subscribe({next:v=>{this.data.set(v);if(v.target){this.roleTitle=v.target.roleTitle;this.roleDescription=v.target.description??'';this.requirements=v.target.requiredSkills.map(x=>({...x}));}},error:e=>this.error.set(e.error?.message??'Could not load career readiness.')});}addRequirement(){this.requirements.push({name:'',targetLevel:'WORKING'});}removeRequirement(i:number){this.requirements.splice(i,1);if(!this.requirements.length)this.addRequirement();}validRequirements(){return this.requirements.some(x=>x.name.trim());}saveTarget(){const requiredSkills=this.requirements.filter(x=>x.name.trim()).map(x=>({name:x.name.trim(),targetLevel:x.targetLevel}));this.api.put('/api/v1/career/target',{roleTitle:this.roleTitle.trim(),description:this.roleDescription.trim()||undefined,requiredSkills}).subscribe({next:()=>this.load(),error:e=>this.error.set(e.error?.message??'Could not save target role.')});}canAddEvidence(){return !!this.skillName.trim()&&(this.evidenceType==='LESSON'?!!this.lessonId:!!this.evidenceTitle.trim());}addEvidence(){const lesson=this.lessons().find(x=>x.id===this.lessonId);const body:any={skillName:this.skillName.trim(),evidenceType:this.evidenceType,title:this.evidenceType==='LESSON'?(lesson?.title??'Completed lesson'):this.evidenceTitle.trim(),description:this.evidenceDescription.trim()||undefined};if(this.evidenceType==='LESSON')body.lessonId=this.lessonId;else if(this.evidenceUrl.trim())body.url=this.evidenceUrl.trim();this.api.post('/api/v1/career/evidence',body).subscribe({next:()=>{this.skillName='';this.lessonId='';this.evidenceTitle='';this.evidenceUrl='';this.evidenceDescription='';this.load();},error:e=>this.error.set(e.error?.message??'Could not add evidence.')});}removeEvidence(id:string){this.api.delete(`/api/v1/career/evidence/${id}`).subscribe(()=>this.load());}label(value:Level){return value.charAt(0)+value.slice(1).toLowerCase();}}
