import { Component, effect, inject, signal } from '@angular/core';
import { Router, RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { AuthService } from './core/auth/auth.service';
import { LoadingService } from './core/loading/loading.service';
import { NotificationCenterService } from './core/notifications/notification-center.service';

type NavGroup = 'workspace' | 'planning' | 'activity' | 'account' | 'admin';

@Component({
  selector: 'app-root', standalone: true, imports: [RouterLink, RouterLinkActive, RouterOutlet], styleUrls: ['./app.component.css','./loader.component.css'],
  template: `
    @if (loading.isLoading()) {<div class="global-api-loader" role="status" aria-live="polite" aria-label="LearnFlow is processing your request"><div class="learning-loader-card"><div class="learning-loader-visual" aria-hidden="true"><span class="learning-orbit learning-orbit-one"></span><span class="learning-orbit learning-orbit-two"></span><span class="learning-orbit learning-orbit-three"></span><div class="learning-logo-shell"><img src="/learnflow-logo.svg" alt=""></div></div><div class="learning-loader-copy"><span class="learning-loader-eyebrow">LearnFlow</span><strong>Learning in motion…</strong><div class="learning-loader-messages" aria-hidden="true"><span>Connecting the next step</span><span>Organising your learning flow</span><span>Getting everything ready</span></div></div><div class="learning-loader-track" aria-hidden="true"><span></span></div><small>Please wait while this action completes.</small></div></div>}
    @if (auth.isAuthenticated()) {
      <div class="jira-workspace"><aside class="workspace-sidebar">
        <a routerLink="/today" class="sidebar-brand" aria-label="LearnFlow today"><img class="brand-logo brand-logo-sidebar" src="/learnflow-logo.svg" alt="" aria-hidden="true"><span><strong>LearnFlow</strong><small>Learning workspace</small></span></a>
        <div class="sidebar-space"><span class="space-avatar">L</span><div><strong>Learning</strong><small>Personal workspace</small></div><span class="space-chevron">⌄</span></div>
        <nav class="sidebar-nav" aria-label="Workspace navigation">
          <section class="nav-group" [class.collapsed]="!groupOpen('workspace')"><button type="button" class="nav-group-toggle" (click)="toggleGroup('workspace')"><span>Workspace</span><span class="group-chevron">⌄</span></button>@if(groupOpen('workspace')){<div class="nav-group-links"><a routerLink="/today" routerLinkActive="active"><span class="nav-icon">☀</span><span>Today</span></a><a routerLink="/dashboard" routerLinkActive="active"><span class="nav-icon">⌂</span><span>Dashboard</span></a><a routerLink="/goals" routerLinkActive="active"><span class="nav-icon">◎</span><span>Goals</span></a><a routerLink="/progress" routerLinkActive="active"><span class="nav-icon">◒</span><span>Progress</span></a><a routerLink="/board" routerLinkActive="active"><span class="nav-icon">▦</span><span>Board</span></a><a routerLink="/learning-paths" routerLinkActive="active"><span class="nav-icon">◆</span><span>Learning paths</span></a></div>}</section>
          <section class="nav-group" [class.collapsed]="!groupOpen('planning')"><button type="button" class="nav-group-toggle" (click)="toggleGroup('planning')"><span>Plan & AI</span><span class="group-chevron">⌄</span></button>@if(groupOpen('planning')){<div class="nav-group-links"><a routerLink="/ai-planner" routerLinkActive="active"><span class="nav-icon">✦</span><span>AI planner</span></a><a routerLink="/import" routerLinkActive="active"><span class="nav-icon">⇧</span><span>Import plan</span></a><a routerLink="/ai-coach" routerLinkActive="active"><span class="nav-icon">✺</span><span>AI coach</span></a><a routerLink="/ai-requests" routerLinkActive="active"><span class="nav-icon">☷</span><span>AI requests</span></a><a routerLink="/ai-usage" routerLinkActive="active"><span class="nav-icon">◔</span><span>AI usage</span></a></div>}</section>
          <section class="nav-group" [class.collapsed]="!groupOpen('activity')"><button type="button" class="nav-group-toggle" (click)="toggleGroup('activity')"><span>Activity</span><span class="group-chevron">⌄</span></button>@if(groupOpen('activity')){<div class="nav-group-links"><a routerLink="/retention" routerLinkActive="active"><span class="nav-icon">↻</span><span>Review queue</span></a><a routerLink="/mastery" routerLinkActive="active"><span class="nav-icon">✓</span><span>Mastery</span></a><a routerLink="/social" routerLinkActive="active"><span class="nav-icon">◎</span><span>Social learning</span></a><a routerLink="/career" routerLinkActive="active"><span class="nav-icon">◇</span><span>Career readiness</span></a><a routerLink="/career/jobs" routerLinkActive="active"><span class="nav-icon">⌕</span><span>Job matching</span></a><a routerLink="/career/applications" routerLinkActive="active"><span class="nav-icon">▤</span><span>Applications</span></a><a routerLink="/study-history" routerLinkActive="active"><span class="nav-icon">◷</span><span>Study history</span></a><a routerLink="/achievements" routerLinkActive="active"><span class="nav-icon">★</span><span>Achievements</span></a><a routerLink="/share-progress" routerLinkActive="active"><span class="nav-icon">↗</span><span>Share progress</span></a><a routerLink="/notifications" routerLinkActive="active"><span class="nav-icon">◉</span><span>Notifications</span>@if(notifications.unreadCount()>0){<em class="sidebar-count">{{notifications.unreadCount()>99?'99+':notifications.unreadCount()}}</em>}</a></div>}</section>
          @if(auth.user()?.role==='admin'){<section class="nav-group admin-group" [class.collapsed]="!groupOpen('admin')"><button type="button" class="nav-group-toggle" (click)="toggleGroup('admin')"><span>Administration</span><span class="group-chevron">⌄</span></button>@if(groupOpen('admin')){<div class="nav-group-links"><a routerLink="/admin" routerLinkActive="active"><span class="nav-icon">◫</span><span>Admin overview</span></a><a routerLink="/admin/entitlements" routerLinkActive="active"><span class="nav-icon">◇</span><span>Entitlements</span></a><a routerLink="/admin/billing" routerLinkActive="active"><span class="nav-icon">¤</span><span>Billing operations</span></a><a routerLink="/admin/system-health" routerLinkActive="active"><span class="nav-icon">♥</span><span>System health</span></a></div>}</section>}
          <section class="nav-group" [class.collapsed]="!groupOpen('account')"><button type="button" class="nav-group-toggle" (click)="toggleGroup('account')"><span>Account</span><span class="group-chevron">⌄</span></button>@if(groupOpen('account')){<div class="nav-group-links"><a routerLink="/profile" routerLinkActive="active"><span class="nav-icon">◎</span><span>Profile & plan</span></a><a routerLink="/billing" routerLinkActive="active"><span class="nav-icon">¤</span><span>Billing</span></a><a routerLink="/settings" routerLinkActive="active"><span class="nav-icon">⚙</span><span>Settings</span></a></div>}</section>
        </nav>
        <div class="sidebar-footer"><button type="button" class="sidebar-account" (click)="logout()"><span class="account-avatar">{{accountInitials()}}</span><span><strong>{{auth.user()?.name||'Account'}}</strong><small>{{auth.user()?.entitlement?.plan||'FREE'}} · {{auth.user()?.role==='admin'?'Administrator':'Log out'}}</small></span><span>↗</span></button></div>
      </aside><div class="workspace-main"><header class="workspace-topbar"><div class="workspace-breadcrumb"><span>LearnFlow</span><span>/</span><strong>Workspace</strong></div><div class="topbar-actions"><a routerLink="/notifications" class="topbar-icon notification-icon">◉@if(notifications.unreadCount()>0){<span class="notification-badge">{{notifications.unreadCount()>99?'99+':notifications.unreadCount()}}</span>}</a><a routerLink="/ai-planner" class="create-work-item">＋ Create lesson plan</a></div></header><main class="shell workspace-shell"><router-outlet /></main></div></div>
      @if(notifications.toast();as toast){<aside class="app-toast" [class.toast-error]="toast.type==='AI_PLAN_FAILED'" aria-live="polite"><div class="toast-icon">{{toast.type==='AI_PLAN_FAILED'?'!':'✓'}}</div><div class="toast-copy"><strong>{{toast.title}}</strong><p>{{toast.message}}</p></div>@if(toast.actionUrl){<button type="button" class="toast-action" (click)="openNotification(toast.actionUrl)">View</button>}<button type="button" class="toast-close" (click)="notifications.dismissToast()">×</button></aside>}
    } @else {<header class="app-header public-header"><a routerLink="/" class="brand-lockup" aria-label="LearnFlow home"><img class="brand-logo brand-logo-public" src="/learnflow-logo.svg" alt="" aria-hidden="true"><span><strong>LearnFlow</strong><small>Learning operations</small></span></a><nav class="public-nav"><a routerLink="/">Home</a><a routerLink="/about">About us</a><a routerLink="/contact">Contact us</a><a routerLink="/login" class="header-login-action">Sign in</a><a routerLink="/register" class="header-primary-action">Get started</a></nav></header><main class="shell public-shell"><router-outlet /></main>}
  `
})
export class AppComponent { readonly auth=inject(AuthService);readonly loading=inject(LoadingService);readonly notifications=inject(NotificationCenterService);private readonly router=inject(Router);private readonly openGroups=signal<Record<NavGroup,boolean>>(this.loadNavState());constructor(){effect(()=>{if(this.auth.isAuthenticated())this.notifications.start();else this.notifications.stop();});}groupOpen(group:NavGroup){return this.openGroups()[group];}toggleGroup(group:NavGroup){const current=this.openGroups();const next={...current,[group]:!current[group]};this.openGroups.set(next);localStorage.setItem('learnflow_nav_groups',JSON.stringify(next));}logout(){this.auth.logout();void this.router.navigateByUrl('/');}openNotification(actionUrl:string){this.notifications.dismissToast();void this.router.navigateByUrl(actionUrl);}accountInitials(){const name=this.auth.user()?.name?.trim();if(!name)return'LF';return name.split(/\s+/).slice(0,2).map(part=>part[0]??'').join('').toUpperCase();}private loadNavState():Record<NavGroup,boolean>{const fallback={workspace:true,planning:true,activity:true,account:false,admin:true};try{const saved=localStorage.getItem('learnflow_nav_groups');return saved?{...fallback,...JSON.parse(saved)}:fallback;}catch{return fallback;}}}
