import { Routes } from '@angular/router';
import { authGuard } from './core/auth/auth.guard';

export const routes: Routes = [
  { path: '', pathMatch: 'full', loadComponent: () => import('./features/home/home.component').then(m => m.HomeComponent) },
  { path: 'about', loadComponent: () => import('./features/about/about.component').then(m => m.AboutComponent) },
  { path: 'contact', loadComponent: () => import('./features/contact/contact.component').then(m => m.ContactComponent) },
  { path: 'share/:token', loadComponent: () => import('./features/sharing/public-progress.component').then(m => m.PublicProgressComponent) },
  { path: 'login', loadComponent: () => import('./features/auth/login.component').then(m => m.LoginComponent) },
  { path: 'register', loadComponent: () => import('./features/auth/register.component').then(m => m.RegisterComponent) },
  { path: 'forgot-password', loadComponent: () => import('./features/auth/forgot-password.component').then(m => m.ForgotPasswordComponent) },
  { path: 'reset-password', loadComponent: () => import('./features/auth/reset-password.component').then(m => m.ResetPasswordComponent) },
  { path: 'onboarding', canActivate: [authGuard], loadComponent: () => import('./features/onboarding/onboarding.component').then(m => m.OnboardingComponent) },
  { path: 'help', canActivate: [authGuard], loadComponent: () => import('./features/help/help.component').then(m => m.HelpComponent) },
  { path: 'today', canActivate: [authGuard], loadComponent: () => import('./features/today/today.component').then(m => m.TodayComponent) },
  { path: 'focus/:lessonId', canActivate: [authGuard], loadComponent: () => import('./features/focus/focus-session.component').then(m => m.FocusSessionComponent) },
  { path: 'assess/:lessonId', canActivate: [authGuard], loadComponent: () => import('./features/assessment/assessment.component').then(m => m.AssessmentComponent) },
  { path: 'mastery', canActivate: [authGuard], loadComponent: () => import('./features/assessment/mastery.component').then(m => m.MasteryComponent) },
  { path: 'study-history', canActivate: [authGuard], loadComponent: () => import('./features/focus/study-history.component').then(m => m.StudyHistoryComponent) },
  { path: 'videos', canActivate: [authGuard], loadComponent: () => import('./features/video-finder/video-finder.component').then(m => m.VideoFinderComponent) },
  { path: 'retention', canActivate: [authGuard], loadComponent: () => import('./features/retention/retention.component').then(m => m.RetentionComponent) },
  { path: 'social', canActivate: [authGuard], loadComponent: () => import('./features/social/social.component').then(m => m.SocialComponent) },
  { path: 'social/groups/:groupId', canActivate: [authGuard], loadComponent: () => import('./features/social/social-group.component').then(m => m.SocialGroupComponent) },
  { path: 'career', canActivate: [authGuard], loadComponent: () => import('./features/career/career.component').then(m => m.CareerComponent) },
  { path: 'career/jobs', canActivate: [authGuard], loadComponent: () => import('./features/career/job-match.component').then(m => m.JobMatchComponent) },
  { path: 'career/applications', canActivate: [authGuard], loadComponent: () => import('./features/career/application-workspace.component').then(m => m.ApplicationWorkspaceComponent) },
  { path: 'career/outcomes', canActivate: [authGuard], loadComponent: () => import('./features/career/career-outcomes.component').then(m => m.CareerOutcomesComponent) },
  { path: 'achievements', canActivate: [authGuard], loadComponent: () => import('./features/achievements/achievements.component').then(m => m.AchievementsComponent) },
  { path: 'dashboard', canActivate: [authGuard], loadComponent: () => import('./features/dashboard/dashboard.component').then(m => m.DashboardComponent) },
  { path: 'progress', canActivate: [authGuard], loadComponent: () => import('./features/progress/progress.component').then(m => m.ProgressComponent) },
  { path: 'goals', canActivate: [authGuard], loadComponent: () => import('./features/goals/goals.component').then(m => m.GoalsComponent) },
  { path: 'share-progress', canActivate: [authGuard], loadComponent: () => import('./features/sharing/share-progress.component').then(m => m.ShareProgressComponent) },
  { path: 'learning-paths', canActivate: [authGuard], loadComponent: () => import('./features/learning-paths/learning-paths.component').then(m => m.LearningPathsComponent) },
  { path: 'learning-paths/:id', canActivate: [authGuard], loadComponent: () => import('./features/learning-paths/learning-path-detail.component').then(m => m.LearningPathDetailComponent) },
  { path: 'board', canActivate: [authGuard], loadComponent: () => import('./features/board/board.component').then(m => m.BoardComponent) },
  { path: 'backlog', canActivate: [authGuard], loadComponent: () => import('./features/backlog/backlog.component').then(m => m.BacklogComponent) },
  { path: 'import', canActivate: [authGuard], loadComponent: () => import('./features/import/import.component').then(m => m.ImportComponent) },
  { path: 'notifications', canActivate: [authGuard], loadComponent: () => import('./features/notifications/notifications.component').then(m => m.NotificationsComponent) },
  { path: 'profile', canActivate: [authGuard], loadComponent: () => import('./features/profile/profile.component').then(m => m.ProfileComponent) },
  { path: 'billing', canActivate: [authGuard], loadComponent: () => import('./features/billing/billing.component').then(m => m.BillingComponent) },
  { path: 'settings', canActivate: [authGuard], loadComponent: () => import('./features/settings/settings.component').then(m => m.SettingsComponent) },
  { path: 'ai-planner', canActivate: [authGuard], loadComponent: () => import('./features/ai-planner/ai-planner.component').then(m => m.AiPlannerComponent) },
  { path: 'ai-requests', canActivate: [authGuard], loadComponent: () => import('./features/ai-requests/ai-requests.component').then(m => m.AiRequestsComponent) },
  { path: 'ai-coach', canActivate: [authGuard], loadComponent: () => import('./features/ai-coach/ai-coach.component').then(m => m.AiCoachComponent) },
  { path: 'ai-usage', canActivate: [authGuard], loadComponent: () => import('./features/ai-usage/ai-usage.component').then(m => m.AiUsageComponent) },
  { path: 'admin', canActivate: [authGuard], loadComponent: () => import('./features/admin/admin.component').then(m => m.AdminComponent) },
  { path: 'admin/entitlements', canActivate: [authGuard], loadComponent: () => import('./features/admin/entitlements.component').then(m => m.EntitlementsComponent) },
  { path: 'admin/billing', canActivate: [authGuard], loadComponent: () => import('./features/admin/billing-settings.component').then(m => m.BillingSettingsComponent) },
  { path: 'admin/billing-events', canActivate: [authGuard], loadComponent: () => import('./features/admin/billing-events.component').then(m => m.BillingEventsComponent) },
  { path: 'admin/system-health', canActivate: [authGuard], loadComponent: () => import('./features/admin/system-health.component').then(m => m.SystemHealthComponent) },
  { path: 'admin/system-limits', canActivate: [authGuard], loadComponent: () => import('./features/admin/system-limits.component').then(m => m.SystemLimitsComponent) },
  { path: '**', redirectTo: '' }
];
