import { Component, OnInit, inject, signal } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { ApiService } from '../../core/services/api.service';

interface BillingEventResponse { counts:Record<string,number>; events:Array<{_id:string;provider:string;eventType:string;status:string;attempts:number;receivedAt:string;processedAt?:string;error?:string;userId?:{name?:string;email?:string};metadata?:Record<string,unknown>}> }

@Component({standalone:true,imports:[MatButtonModule],template:`
<section class="page-enter events-page"><div class="page-head"><div><span class="eyebrow">Administration</span><h1>Billing webhook events</h1><p class="muted">Inspect provider deliveries, retries and processing outcomes without digging through Render logs.</p></div><button mat-stroked-button (click)="load()">Refresh</button></div>
@if(error()){<div class="error">{{error()}}</div>}
<div class="metrics"><div><b>{{count('PROCESSED')}}</b><span>Processed</span></div><div><b>{{count('FAILED')}}</b><span>Failed</span></div><div><b>{{count('RECEIVED')}}</b><span>Received</span></div><div><b>{{count('IGNORED')}}</b><span>Ignored</span></div></div>
<article class="panel">@for(event of data()?.events??[];track event._id){<div class="event"><div><strong>{{event.eventType}}</strong><small>{{event.provider}} · {{date(event.receivedAt)}}</small></div><span class="status" [class.failed]="event.status==='FAILED'">{{event.status}}</span><span>Attempt {{event.attempts}}</span><div><strong>{{event.userId?.name||'Unmapped'}}</strong><small>{{event.userId?.email||event.error||'—'}}</small></div></div>}@empty{<p class="muted">No billing webhook events recorded yet.</p>}</article></section>`,styles:[`.events-page{max-width:1200px;margin:auto}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0}.metrics div,.panel{background:#fff;border:1px solid #e1e6ed;border-radius:16px;padding:18px}.metrics b{display:block;font-size:1.5rem;color:#10233f}.metrics span,.event small{color:#667085;font-size:.75rem}.event{display:grid;grid-template-columns:2fr .8fr .8fr 2fr;gap:12px;padding:12px 0;border-top:1px solid #edf0f3;align-items:center}.event div{display:flex;flex-direction:column}.status{font-size:.7rem;font-weight:800;padding:5px 8px;border-radius:999px;background:#ecfdf3;color:#027a48;width:max-content}.status.failed{background:#fff1f0;color:#b42318}.error{background:#fff1f0;color:#b42318;padding:12px;border-radius:10px}@media(max-width:800px){.metrics{grid-template-columns:1fr 1fr}.event{grid-template-columns:1fr 1fr}}`]})
export class BillingEventsComponent implements OnInit{private api=inject(ApiService);readonly data=signal<BillingEventResponse|null>(null);readonly error=signal('');ngOnInit(){this.load();}load(){this.error.set('');this.api.get<BillingEventResponse>('/api/v1/admin/billing-events').subscribe({next:v=>this.data.set(v),error:e=>this.error.set(e?.error?.message??'Unable to load billing events.')});}count(status:string){return this.data()?.counts?.[status]??0;}date(v:string){return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(v));}}
