import { Component, OnInit, computed, inject, signal } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { ApiService } from '../../core/services/api.service';

interface BillingEventResponse { counts:Record<string,number>; events:Array<{_id:string;provider:string;eventType:string;status:string;attempts:number;receivedAt:string;processedAt?:string;error?:string;userId?:{name?:string;email?:string};metadata?:Record<string,unknown>}> }

@Component({standalone:true,imports:[MatButtonModule],template:`
<section class="page-enter events-page"><div class="page-head"><div><span class="eyebrow">Administration</span><h1>Billing webhook events</h1><p class="muted">Inspect provider deliveries, retries and processing outcomes without digging through Render logs.</p></div><button mat-stroked-button (click)="load()">Refresh</button></div>
@if(error()){<div class="error">{{error()}}</div>}
<div class="metrics"><div><b>{{count('PROCESSED')}}</b><span>Processed</span></div><div><b>{{count('FAILED')}}</b><span>Failed</span></div><div><b>{{count('RECEIVED')}}</b><span>Received</span></div><div><b>{{count('IGNORED')}}</b><span>Ignored</span></div></div>
<article class="panel"><div class="panel-head"><div><span class="mini-label">Event log</span><h3>Recent webhook activity</h3></div><small>Showing {{rangeStart()}}–{{rangeEnd()}} of {{events().length}}</small></div>@for(event of paged();track event._id){<div class="event"><div class="event-main"><strong>{{friendly(event.eventType)}}</strong><small>{{event.provider}} · {{date(event.receivedAt)}}</small></div><div class="event-status"><span class="status" [class.failed]="event.status==='FAILED'">{{friendly(event.status)}}</span><small>Attempt {{event.attempts}}</small></div><div class="event-user"><strong>{{event.userId?.name||'Unmapped user'}}</strong><small>{{event.userId?.email||event.error||'No additional detail'}}</small></div></div>}@empty{<p class="muted">No billing webhook events recorded yet.</p>}@if(pageCount()>1){<footer class="pager"><button mat-stroked-button type="button" (click)="setPage(page()-1)" [disabled]="page()===1">Previous</button><span>Page {{page()}} of {{pageCount()}}</span><button mat-stroked-button type="button" (click)="setPage(page()+1)" [disabled]="page()===pageCount()">Next</button></footer>}</article></section>`,styles:[`.events-page{max-width:1200px;margin:auto}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0}.metrics div,.panel{background:#fff;border:1px solid #e1e6ed;border-radius:16px;padding:18px}.metrics b{display:block;font-size:1.5rem;color:#10233f}.metrics span,.event small{color:#667085;font-size:.75rem}.panel-head{display:flex;justify-content:space-between;align-items:end;gap:12px;margin-bottom:6px}.panel-head h3{margin:3px 0 0;color:#10233f}.panel-head small{color:#7a869a}.event{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(120px,.5fr) minmax(0,1fr);gap:14px;padding:13px 0;border-top:1px solid #edf0f3;align-items:center}.event-main,.event-user,.event-status{display:flex;flex-direction:column;min-width:0}.event strong,.event small{overflow-wrap:anywhere}.status{font-size:.7rem;font-weight:800;padding:5px 8px;border-radius:999px;background:#ecfdf3;color:#027a48;width:max-content}.status.failed{background:#fff1f0;color:#b42318}.event-status small{margin-top:4px}.error{background:#fff1f0;color:#b42318;padding:12px;border-radius:10px}.pager{display:flex;justify-content:flex-end;align-items:center;gap:10px;padding-top:14px;border-top:1px solid #edf0f3}.pager span{font-size:.72rem;color:#667085}@media(max-width:800px){.metrics{grid-template-columns:1fr 1fr}.event{grid-template-columns:1fr}.panel-head{align-items:flex-start;flex-direction:column}.pager{justify-content:space-between}}`]})
export class BillingEventsComponent implements OnInit{private api=inject(ApiService);readonly data=signal<BillingEventResponse|null>(null);readonly error=signal('');readonly page=signal(1);readonly pageSize=10;readonly events=computed(()=>this.data()?.events??[]);readonly paged=computed(()=>{const start=(this.page()-1)*this.pageSize;return this.events().slice(start,start+this.pageSize);});ngOnInit(){this.load();}load(){this.error.set('');this.api.get<BillingEventResponse>('/api/v1/admin/billing-events').subscribe({next:v=>{this.data.set(v);this.page.set(1);},error:e=>this.error.set(e?.error?.message??'Unable to load billing events.')});}count(status:string){return this.data()?.counts?.[status]??0;}pageCount(){return Math.max(1,Math.ceil(this.events().length/this.pageSize));}setPage(v:number){this.page.set(Math.min(Math.max(1,v),this.pageCount()));}rangeStart(){return this.events().length?(this.page()-1)*this.pageSize+1:0;}rangeEnd(){return Math.min(this.page()*this.pageSize,this.events().length);}friendly(value:string){const v=value.toLowerCase().replaceAll('_',' ');return v.charAt(0).toUpperCase()+v.slice(1);}date(v:string){return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(v));}}
