import { Component, OnInit, inject, signal } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { ApiService } from '../../core/services/api.service';

interface HealthResponse{status:string;checkedAt:string;services:Record<string,{status:string;[key:string]:unknown}>;}
@Component({standalone:true,imports:[MatButtonModule],template:`
<section class="health page-enter"><div class="page-head"><div><span class="eyebrow">Operations</span><h1>System health</h1><p class="muted">A safe production snapshot without exposing secrets.</p></div><button mat-stroked-button (click)="load()">Refresh</button></div>
@if(health();as h){<div class="overall" [class.bad]="h.status!=='HEALTHY'"><strong>{{h.status}}</strong><span>Checked {{format(h.checkedAt)}}</span></div><div class="grid">@for(item of entries(h.services);track item[0]){<article><span>{{item[0]}}</span><strong>{{item[1].status}}</strong><pre>{{details(item[1])}}</pre></article>}</div>}@else{<div class="loading">Loading system health…</div>}</section>`,styles:[`.health{max-width:1050px;margin:0 auto}.overall{display:flex;justify-content:space-between;align-items:center;padding:16px 18px;border-radius:14px;background:#eef8f3;color:#176344;margin-bottom:16px}.overall.bad{background:#fff6e8;color:#9a5a05}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.grid article{padding:18px;border:1px solid #dfe5ed;border-radius:16px;background:#fff}.grid span{display:block;text-transform:uppercase;font-size:.68rem;font-weight:800;color:#7a869a}.grid strong{display:block;margin:5px 0;color:#10233f}.grid pre{white-space:pre-wrap;color:#66758a;font:inherit;font-size:.75rem}.loading{padding:28px;border:1px dashed #ccd7e5;border-radius:14px}@media(max-width:650px){.grid{grid-template-columns:1fr}}`]})
export class SystemHealthComponent implements OnInit{private readonly api=inject(ApiService);readonly health=signal<HealthResponse|null>(null);ngOnInit():void{this.load();}load():void{this.api.get<HealthResponse>('/api/v1/admin/system-health').subscribe(value=>this.health.set(value));}entries(value:HealthResponse['services']){return Object.entries(value);}details(value:Record<string,unknown>):string{const rest={...value};delete rest['status'];return Object.entries(rest).map(([k,v])=>`${k}: ${String(v)}`).join('\n');}format(v:string):string{return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(v));}}
