import { Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { ApiService } from '../../core/services/api.service';
import { AuthService } from '../../core/auth/auth.service';

type UserRef={_id:string;name:string;email:string};
type Connection={_id:string;requesterId:UserRef;recipientId:UserRef;status:string};
type Group={_id:string;name:string;description?:string;joinCode:string;memberIds:string[]};
type Overview={incoming:Connection[];outgoing:Connection[];partners:Connection[];groups:Group[]};

@Component({standalone:true,imports:[FormsModule,RouterLink,MatButtonModule],template:`
<section class="social page-enter"><div class="page-head"><div><span class="eyebrow">Social learning</span><h1>Accountability without the noise.</h1><p class="muted">Connect with people you trust, form small study groups and keep momentum visible on your terms.</p></div></div>
@if(error()){<div class="error">{{error()}}</div>}
<div class="grid two"><article class="card"><span class="mini-label">Accountability partner</span><h2>Invite a LearnFlow user</h2><p class="muted">Invites only work for existing LearnFlow accounts. No external email is sent.</p><div class="inline"><input [(ngModel)]="partnerEmail" type="email" placeholder="person@example.com"><button mat-flat-button class="primary-cta" (click)="invite()" [disabled]="!partnerEmail.trim()">Invite</button></div>
@if(data();as d){@if(d.incoming.length){<h3>Incoming</h3>@for(item of d.incoming.slice(0,4);track item._id){<div class="row"><div><strong>{{item.requesterId.name}}</strong><small>{{item.requesterId.email}}</small></div><span><button mat-stroked-button (click)="respond(item,'ACCEPTED')">Accept</button><button mat-button (click)="respond(item,'DECLINED')">Decline</button></span></div>}}<div class="section-title"><h3>Partners</h3><small>{{d.partners.length}} total</small></div>@for(item of pagedPartners();track item._id){<div class="row"><div><strong>{{partnerName(item)}}</strong><small>{{partnerEmailText(item)}}</small></div><span class="pill">Connected</span></div>}@empty{<p class="muted">No accountability partners yet.</p>}@if(partnerPageCount()>1){<footer class="mini-pager"><button type="button" (click)="setPartnerPage(partnerPage()-1)" [disabled]="partnerPage()===1">‹</button><span>{{partnerPage()}} / {{partnerPageCount()}}</span><button type="button" (click)="setPartnerPage(partnerPage()+1)" [disabled]="partnerPage()===partnerPageCount()">›</button></footer>}}</article>
<article class="card"><span class="mini-label">Study groups</span><h2>Create a small group</h2><div class="stack"><input [(ngModel)]="groupName" placeholder="e.g. React Interview Prep"><textarea [(ngModel)]="groupDescription" rows="3" placeholder="What is this group learning together?"></textarea><button mat-flat-button class="primary-cta" (click)="createGroup()" [disabled]="!groupName.trim()">Create group</button></div><div class="join"><input [(ngModel)]="joinCode" placeholder="Join code"><button mat-stroked-button (click)="join()" [disabled]="!joinCode.trim()">Join group</button></div></article></div>
<article class="card groups"><div class="section-head"><div><span class="mini-label">Your groups</span><h2>Shared learning spaces</h2></div>@if(data();as d){<small>{{d.groups.length}} total</small>}</div>@if(data();as d){<div class="group-list">@for(group of pagedGroups();track group._id){<a [routerLink]="['/social/groups',group._id]"><div><strong>{{group.name}}</strong><small>{{group.description || 'No description'}}</small></div><span>{{group.memberIds.length}} member{{group.memberIds.length===1?'':'s'}} · {{group.joinCode}}</span></a>}@empty{<div class="empty">Create or join a group to start collaborating.</div>}</div>@if(groupPageCount()>1){<footer class="pager"><button mat-stroked-button type="button" (click)="setGroupPage(groupPage()-1)" [disabled]="groupPage()===1">Previous</button><span>Page {{groupPage()}} of {{groupPageCount()}}</span><button mat-stroked-button type="button" (click)="setGroupPage(groupPage()+1)" [disabled]="groupPage()===groupPageCount()">Next</button></footer>}}</article>
</section>`,styles:[`.social{max-width:1100px;margin:0 auto}.grid.two{display:grid;grid-template-columns:1fr 1fr;gap:16px}.card{background:#fff;border:1px solid #dfe5ed;border-radius:18px;padding:20px;margin-bottom:18px;overflow:hidden}.card h2{color:#10233f;margin:6px 0 12px}.card h3{font-size:.8rem;margin:18px 0 6px;color:#526178;text-transform:uppercase}.inline,.join{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px}.stack{display:grid;gap:8px}.join{margin-top:10px}.card input,.card textarea{border:1px solid #d7dde7;border-radius:10px;padding:11px;font:inherit;box-sizing:border-box;min-width:0}.row{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:10px 0;border-top:1px solid #edf1f5}.row div{display:flex;flex-direction:column;min-width:0}.row strong,.row small{overflow-wrap:anywhere}.row small,.group-list small{color:#7a869a}.pill{padding:5px 8px;border-radius:999px;background:#eaf7ef;color:#216e4e;font-size:.68rem;font-weight:800}.section-title,.section-head{display:flex;justify-content:space-between;align-items:end;gap:10px}.section-title small,.section-head>small{color:#7a869a}.group-list{display:grid}.group-list a{display:flex;justify-content:space-between;gap:16px;padding:14px 0;border-top:1px solid #edf1f5;text-decoration:none;color:#10233f}.group-list a>div{display:flex;flex-direction:column;min-width:0}.group-list a strong,.group-list a small{overflow-wrap:anywhere}.group-list a>span{color:#526178;font-size:.72rem}.mini-pager,.pager{display:flex;justify-content:center;align-items:center;gap:8px;padding-top:10px;border-top:1px solid #edf1f5}.mini-pager button{width:30px;height:30px;border:1px solid #d0d5dd;border-radius:8px;background:#fff}.mini-pager span,.pager span{font-size:.7rem;color:#667085}.pager{justify-content:flex-end}.empty,.error{padding:14px;border-radius:12px}.empty{background:#f7f9fc;color:#66758a}.error{background:#fff1f0;color:#a61b1b;margin-bottom:14px}@media(max-width:800px){.grid.two{grid-template-columns:1fr}.group-list a{flex-direction:column}.pager{justify-content:space-between}}@media(max-width:520px){.inline,.join{grid-template-columns:1fr}.row{align-items:flex-start;flex-direction:column}.row>span{display:flex;gap:6px;flex-wrap:wrap}}`]
})
export class SocialComponent implements OnInit{private readonly api=inject(ApiService);private readonly auth=inject(AuthService);readonly data=signal<Overview|null>(null);readonly error=signal('');readonly partnerPage=signal(1);readonly groupPage=signal(1);readonly pageSize=5;readonly pagedPartners=computed(()=>{const rows=this.data()?.partners??[];const s=(this.partnerPage()-1)*this.pageSize;return rows.slice(s,s+this.pageSize)});readonly pagedGroups=computed(()=>{const rows=this.data()?.groups??[];const s=(this.groupPage()-1)*this.pageSize;return rows.slice(s,s+this.pageSize)});partnerEmail='';groupName='';groupDescription='';joinCode='';ngOnInit(){this.load();}load(){this.api.get<Overview>('/api/v1/social/overview').subscribe({next:v=>{this.data.set(v);this.setPartnerPage(this.partnerPage());this.setGroupPage(this.groupPage());},error:e=>this.error.set(e.error?.message??'Could not load social learning.')});}partnerPageCount(){return Math.max(1,Math.ceil((this.data()?.partners.length??0)/this.pageSize));}groupPageCount(){return Math.max(1,Math.ceil((this.data()?.groups.length??0)/this.pageSize));}setPartnerPage(v:number){this.partnerPage.set(Math.min(Math.max(1,v),this.partnerPageCount()));}setGroupPage(v:number){this.groupPage.set(Math.min(Math.max(1,v),this.groupPageCount()));}invite(){this.api.post('/api/v1/social/partners/invite',{email:this.partnerEmail.trim()}).subscribe({next:()=>{this.partnerEmail='';this.load();},error:e=>this.error.set(e.error?.message??'Could not send invitation.')});}respond(item:Connection,status:'ACCEPTED'|'DECLINED'){this.api.patch(`/api/v1/social/partners/${item._id}/respond`,{status}).subscribe(()=>this.load());}createGroup(){this.api.post('/api/v1/social/groups',{name:this.groupName.trim(),description:this.groupDescription.trim()||undefined}).subscribe({next:()=>{this.groupName='';this.groupDescription='';this.groupPage.set(1);this.load();},error:e=>this.error.set(e.error?.message??'Could not create group.')});}join(){this.api.post('/api/v1/social/groups/join',{joinCode:this.joinCode.trim()}).subscribe({next:()=>{this.joinCode='';this.groupPage.set(1);this.load();},error:e=>this.error.set(e.error?.message??'Could not join group.')});}partnerName(item:Connection){const me=item.requesterId?.email===this.auth.user()?.email;return me?item.recipientId?.name:item.requesterId?.name;}partnerEmailText(item:Connection){const me=item.requesterId?.email===this.auth.user()?.email;return me?item.recipientId?.email:item.requesterId?.email;}}
